name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting:
        * search [existing issues](https://github.com/your-username/telescope-gitignore.nvim/issues)
        * ensure that telescope-gitignore.nvim is updated to the latest version

  - type: textarea
    attributes:
      label: 'Is your feature request related to a problem? Please describe.'
      description: 'A clear and concise description of what the problem is.'
      placeholder: 'I am always frustrated when [...]'
    validations:
      required: true

  - type: textarea
    attributes:
      label: 'Describe the solution you would like'
      description: 'A clear and concise description of what you want to happen.'
      placeholder: |
        I would like to be able to [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: 'Describe alternatives you have considered'
      description: 'A clear and concise description of any alternative solutions or features you have considered.'
      placeholder: |
        I have tried [...] but it doesn't work because [...]

  - type: textarea
    attributes:
      label: 'Additional context'
      description: 'Add any other context or screenshots about the feature request here.'
      placeholder: |
        Any additional information that might be helpful.